<?php $this->partial("header"); ?>

	<header class="bg-primary text-white">
		<div class="container text-center">
			<h1>404</h1>
			<p class="lead">Sorry We could not find what you were looking for</p>
		</div>
	</header>

    <section id="about">
      <div class="container">
        <div class="row">
          <div class="col-lg-8 mx-auto">
            <h2 class="text-center">. We were feeding our fishes, why dont you try again.</h2>
          </div>
        </div>
      </div>
    </section>

<?php $this->partial("footer"); ?>
