<?php $this->partial("header"); ?>

	<header class="bg-primary text-white not-main">
		<div class="container text-center">
			<h1>Aquariums</h1>
			<p class="lead"><a class="btn btn-success" href="<?php echo $this->url->get('/shop/'.$shop->getId().'/aquarium/add'); ?>" role="button">Add New</a></p>
		</div>
	</header>

    <section id="about">
      <div class="container">
        <div class="row">
          <div class="col-lg-8 mx-auto ">
<!--            <h2 class="">Aquariums</h2>-->
<!--            <p class="lead">This is a great place to talk about your webpage. This template is purposefully unstyled so you can use it as a boilerplate or starting point for you own landing page designs! This template features:</p>-->
	          <?php $this->partial("flash_messages"); ?>
	          <div class="table-responsive">
		          <?php
		          if(isset($aquariums) && count($aquariums) > 0 ) :
		          	?>
			     <table class="table">
				  <thead>
					  <tr>
						  <th scope="col">ID</th>
						  <th scope="col">Capacity</th>
						  <th scope="col">Shape</th>
						  <th scope="col">Material</th>
						  <th scope="col">Stock</th>
						  <th scope="col">Created</th>
						  <th scope="col">Updated</th>
						  <th scope="col">Operations</th>
					  </tr>
				  </thead>
				  <tbody>
				   <?php
						  /**@var $aquarium \PetFishCo\Frontend\Models\DTO\AquariumInstance*/
						  /**@var $shop \PetFishCo\Frontend\Models\DTO\Shop*/
					  foreach ($aquariums as $index => $aquarium): ?>
						  <tr>
							  <th scope="row"><?php echo $aquarium->getId();?></th>
							  <td><?php echo $aquarium->getCapacity($shop->getMeasureSystem());?></td>
							  <td><?php echo $aquarium->getAquariumShape();?></td>
							  <td><?php echo $aquarium->getAquariumMaterial();?></td>
							  <td><?php echo $aquarium->getAmount();?></td>
							  <td><?php echo $aquarium->getCreatedAt();?></td>
							  <td><?php echo $aquarium->getUpdatedAt();?></td>
							  <td>
								  <a href="<?php echo $this->url->get('/shop/'.$shop->getId().'/aquarium/' . $aquarium->getId()); ?>">View</a>
								  <a href="<?php echo $this->url->get('/shop/'.$shop->getId().'/aquarium/' . $aquarium->getId() . '/edit'); ?>">Edit</a>
							  </td>
						  </tr>
					  <?php endforeach; ?>

			          </tbody>
		          </table>
		          <?php endif; ?>
	          </div>
          </div>
        </div>
      </div>
    </section>

<?php $this->partial("footer"); ?>
