    <!-- Footer -->
    <footer class="py-5 bg-dark">
      <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; PetFishCo 2018</p>
      </div>
      <!-- /.container -->
    </footer>

    <!-- Bootstrap core JavaScript -->
    <script src="<?php echo $this->url->get('vendor/jquery/jquery.min.js')?>"></script>
    <script src="<?php echo $this->url->get('vendor/bootstrap/js/bootstrap.bundle.min.js')?>"></script>

    <!-- Plugin JavaScript -->
    <script src="<?php echo $this->url->get('vendor/jquery-easing/jquery.easing.min.js')?>"></script>

    <!-- Custom JavaScript for this theme -->
    <script src="<?php echo $this->url->get('js/scrolling-nav.js')?>"></script>
