    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" id="mainNav">
      <div class="container">
        <a class="navbar-brand js-scroll-trigger" href="<?php echo $this->url->get('/');?>">PetFishCo <?php echo isset($shop) ? ' - ' . $shop->getName() : ''; ?></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
	        <ul class="navbar-nav ml-auto">
		        <li class="nav-item">
			        <a class="nav-link" href="javascript::void()">Units:</a>
		        </li>
		        <li class="nav-item ">
			        <a class="nav-link " href="javascript::void()">Gallons ( gal.)</a>
		        </li>
		        <li class="nav-item active">
			        <a class="nav-link" href="javascript::void()">Liters ( L )</a>
		        </li>
	        </ul>
        </div>
      </div>
    </nav>